### ISSUE TITLE
Error: Cannot find module '/mnt/ssd/home/stacks/stacks-blockchain/report

### ISSUE THREAD

**Issue by randyramig** [psq/stacks-dump#12]
Having issues running this:

```stacks@slowdive:~/stacks-blockchain$ node report /tmp/stacks-testnet-ace41dd899f1c68f```

```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/mnt/ssd/home/stacks/stacks-blockchain/report'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}```

**Comment by psq** [comment]
you are not in the `stacks-dump` folder, it says you are in the `stacks-blockchain` folder.

**Comment by randyramig** [comment]
Thanks, @psq - when I run it from the stacks-dump folder I get:

```stacks@slowdive:~/stacks-dump$ node report /tmp/stacks-testnet-ace41dd899f1c68f```
```
file:///mnt/ssd/home/stacks/stacks-dump/report.js:402
const stmt_all_staging_blocks = staging_db.prepare('SELECT * FROM staging_blocks')
                                           ^
SqliteError: no such table: staging_blocks
    at file:///mnt/ssd/home/stacks/stacks-dump/report.js:402:44
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)```

**Comment by psq** [comment]
have you read the readme all the way to the end before asking questions?

**Comment by randyramig** [comment]
Apparently not.  Got it working now, thanks -- not used to having the gotchas at the end of the doc.
