### ISSUE TITLE
TypeError: Cannot read property 'parent_burn_header_hash' of undefined

### ISSUE THREAD

**Issue by pwecker** [psq/stacks-dump#14]
Running stacks-dump on the linked data dir created by v24.3.2.0-xenon/linux-x64.zip binary yields following error:

```
(node:106561) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'parent_burn_header_hash' of undefined
    at process_snapshots (file:///home/ubuntu/stacks-dump/report.js:583:80)
    at file:///home/ubuntu/stacks-dump/report.js:772:3
    at file:///home/ubuntu/stacks-dump/report.js:924:3
    at ModuleJob.run (internal/modules/esm/module_job.js:146:23)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:106561) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:106561) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

data dir: https://demo.vmg.nyc/stx/qa/datadir.zip

**Comment by psq** [comment]
thanks for the file, this will be fix when I commit the next set of changes in a few hours.  That was a trivial fix.

Interestingly, and I think you said you copied the files while the node was running, I get `SqliteError: database disk image is malformed` later on after fixing the crash...

**Comment by pwecker** [comment]
Oh, I had absolutely copied the files while the stacks node was still running, happy to provide a further zip from a paused state if it helps at all. Thanks!
