### ISSUE TITLE
TypeError: Cannot read property 'block_commits_distances' of undefined

### ISSUE THREAD

**Issue by friedger** [psq/stacks-dump#22]
file:///home/ubuntu/stacks-dump/report.js:749
      block.block_commits_distances += block_parent_distance
      ^

TypeError: Cannot read property 'block_commits_distances' of undefined
    at process_block_commits (file:///home/ubuntu/stacks-dump/report.js:749:7)
    at file:///home/ubuntu/stacks-dump/report.js:924:3
    at file:///home/ubuntu/stacks-dump/report.js:1212:3
    at ModuleJob.run (node:internal/modules/esm/module_job:152:23)
    at async Loader.import (node:internal/modules/esm/loader:166:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)

**Comment by psq** [comment]
I think this was fixed
