### ISSUE TITLE
Stacks-dump doesn't work on a testnet

### ISSUE THREAD

**Issue by MaksimalistT** [psq/stacks-dump#24]
Running a miner on a testnet, try node report
got error 

> /home/ec2-user/stacks-dump/node_modules/better-sqlite3/lib/database.js:32
		throw new TypeError('Cannot open database because the directory does not exist');
TypeError: Cannot open database because the directory does not exist
    at new Database (/home/ec2-user/stacks-dump/node_modules/better-sqlite3/lib/database.js:32:9)
    at file:///home/ec2-user/stacks-dump/report.js:500:22
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)

**Comment by psq** [comment]
was using wrong option
